
theme: jekyll-theme-slate
title: Emmanuel Kidando
#Name
#name: Emmanuel Kidando

# Bio
description: Data Analytics & Civil Engineering, Florida State University

# description: Florida State University
